### ISSUE TITLE
Operator overloads

### ISSUE THREAD

**Issue by rhysd** [rhysd/Dachs#54]
At least below operators should be available to overload.

- Binary

```
>> << <= >= == != && || * / % + - < > & ^ |
```

- Unary

```
+ - ~ !
```

- Others

```
[]
```

Function overload example:

```
class X
    value

    func +(rhs : X)
        ret value + rhs.value
    end

    # Unary +
    func +
        ret value
    end

    oper +
        
    end
end

func -(lhs : X, rhs : X)
    ret lhs.value - rhs.value
end

func main
    a := new X{42}
    b := new X{10}

    # This invokes a.+(b)
    c := a + b

    # This invokes -(a, b)
    d := a - b

    # This invokes built-in operator for 'int'
    e := a.value + b.value
end
```

**Comment by rhysd** [comment]
## TODOs

- [ ] Check the number of binary functions' arguments
- [ ] Implementation for `ast::node::binary_expr`
- [ ] Implementation for `case` statements (which uses `==` emplicitly)
- [ ] Implementation for compound assignments like `+=`
- [ ] Implementation for `[]` operator
- [ ] Check the number of unary functions' arguments
- [ ] Implementation for `ast::node::unary_expr`
- [ ] Consider more operators like `>>=`, `=<<`, `$` and so on.  (Are they necessary?)

**Comment by rhysd** [comment]
> Consider more operators like >>=, =<<, $ and so on. (Are they necessary?)

I think this requires more consideration.  I'll remain it.
